all:
  children:
    webservers:
      hosts:
        web-1:
          ansible_host: 192.168.10.11
        web-2:
          ansible_host: 192.168.10.12
    monitoring:
      hosts:
        prometheus:
          ansible_host: 192.168.10.13
        grafana:
          ansible_host: 192.168.10.14
    logging:
      hosts:
        elasticsearch:
          ansible_host: 192.168.10.15
        kibana:
          ansible_host: 192.168.10.16