- import_tasks: ../../common/tasks/install_docker.yml

- name: Create data directory for Elasticsearch
  file:
    path: /opt/elasticsearch/data
    state: directory
    recurse: yes

- name: Run Elasticsearch container
  community.docker.docker_container:
    name: elasticsearch
    image: elasticsearch:7.17.12
    ports:
      - "9200:9200"
    env:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - /opt/elasticsearch/data:/usr/share/elasticsearch/data
    restart_policy: always