- hosts: webservers
  become: true
  roles:
    - nginx
    - filebeat
    - exporters

- hosts: monitoring
  become: true
  roles:
    - prometheus
    - grafana

- hosts: logging
  become: true
  roles:
    - elasticsearch
    - kibana