- name: apt update
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy static site files
  copy:
    src: files/
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: 0644

- name: Enable and start nginx
  service:
    name: nginx
    state: started
    enabled: yes