- import_tasks: ../../common/tasks/install_docker.yml

- name: Run Kibana container
  community.docker.docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.14
    ports:
      - "5601:5601"
    env:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    links:
      - elasticsearch
    restart_policy: always